export const PES_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
  "function liquidityWallet() view returns (address)",
  "function operationsWallet() view returns (address)",
  "function tradingEnabled() view returns (bool)",
  "function buyFees() view returns (uint16 liquidityBps, uint16 operationsBps, uint16 burnBps)",
  "function sellFees() view returns (uint16 liquidityBps, uint16 operationsBps, uint16 burnBps)",
  "function totalBuyFeeBps() view returns (uint16)",
  "function totalSellFeeBps() view returns (uint16)",
  "function automatedMarketMakerPairs(address pair) view returns (bool)",
  "function isExcludedFromFees(address account) view returns (bool)",
  "function setTradingEnabled(bool enabled)",
  "function setAutomatedMarketMakerPair(address pair, bool enabled)",
  "function setExcludedFromFees(address account, bool excluded)",
  "function setFeeWallets(address newLiquidityWallet, address newOperationsWallet)",
  "function setFeeRates(bool isBuyFee, uint16 liquidityBps, uint16 operationsBps, uint16 burnBps)",
  "function pause()",
  "function unpause()",
];

export const PRESALE_ABI = [
  "function owner() view returns (address)",
  "function paused() view returns (bool)",
  "function pesToken() view returns (address)",
  "function paymentToken() view returns (address)",
  "function fundsWallet() view returns (address)",
  "function paymentPerPackage() view returns (uint256)",
  "function pesPerPackage() view returns (uint256)",
  "function maxPackages() view returns (uint256)",
  "function publicPackageCap() view returns (uint256)",
  "function perWalletPackageLimit() view returns (uint256)",
  "function saleStart() view returns (uint64)",
  "function saleEnd() view returns (uint64)",
  "function launchTime() view returns (uint64)",
  "function publicPackagesSold() view returns (uint256)",
  "function totalPackagesAllocated() view returns (uint256)",
  "function totalTokensAllocated() view returns (uint256)",
  "function totalTokensClaimed() view returns (uint256)",
  "function unclaimedAllocatedTokens() view returns (uint256)",
  "function allocations(address account) view returns (uint256 packages, uint256 tokens, uint256 claimed)",
  "function vestedAmount(address account) view returns (uint256)",
  "function claimableAmount(address account) view returns (uint256)",
  "function purchasePackages(uint256 packages)",
  "function claim() returns (uint256)",
  "function grantAllocation(address account, uint256 packages)",
  "function grantAllocations(address[] accounts, uint256[] packagesList)",
  "function setSaleWindow(uint64 newSaleStart, uint64 newSaleEnd)",
  "function setLaunchTime(uint64 newLaunchTime)",
  "function setFundsWallet(address newFundsWallet)",
  "function setPackageConfig(uint256 newPaymentPerPackage, uint256 newPesPerPackage, uint256 newMaxPackages, uint256 newPublicPackageCap, uint256 newPerWalletPackageLimit)",
  "function pause()",
  "function unpause()",
];

export const ERC20_ABI = [
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
];

